// BURN — Share landing page + Open Graph metadata
// Renders a crawlable HTML page for a roast submission so links shared on
// WhatsApp/Telegram/Twitter/etc. get a proper preview card.
//
// Usage: GET /functions/v1/roast-page?id=<submission uuid>
//
// Uses SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (auto-injected in the
// Supabase Edge runtime) to look up the submission. The og:image points at
// the og-image function, which generates the PNG card.
//
// Deploy: supabase functions deploy roast-page --no-verify-jwt

import { corsHeaders } from '../_shared/cors.ts';

interface SubmissionRow {
  id: string;
  bucket: string;
  lang: string;
  response_line: string;
  created_at: string;
}

const BUCKET_EMOJI: Record<string, string> = {
  'failed-exam': '📝', 'breakup': '💔', 'job-hunt': '🔍',
  'work-stress': '💼', 'nothing-works': '🌀', 'loneliness': '🫥',
  'family-pressure': '👨‍👩‍👧', 'health-fitness': '💪', 'money': '💸',
  'social-media': '📱', 'general': '☠️',
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function truncate(value: string, max: number): string {
  const s = value.replace(/\s+/g, ' ').trim();
  return s.length > max ? `${s.slice(0, max - 1).trimEnd()}…` : s;
}

async function fetchSubmission(id: string): Promise<SubmissionRow | null> {
  const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? '';
  const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
  if (!supabaseUrl || !serviceKey) return null;

  const res = await fetch(
    `${supabaseUrl}/rest/v1/submissions?id=eq.${encodeURIComponent(id)}&select=id,bucket,lang,response_line,created_at&limit=1`,
    {
      headers: {
        'apikey': serviceKey,
        'Authorization': `Bearer ${serviceKey}`,
      },
    },
  );
  if (!res.ok) return null;
  const rows = await res.json() as SubmissionRow[];
  return rows?.[0] ?? null;
}

function renderPage(row: SubmissionRow, supabaseUrl: string, siteUrl: string): string {
  const roast = truncate(row.response_line || 'Your roast is ready.', 200);
  const emoji = BUCKET_EMOJI[row.bucket] ?? '☠️';
  const bucketLabel = row.bucket.replace(/-/g, ' ');

  const ogImage = `${supabaseUrl}/functions/v1/og-image?text=${encodeURIComponent(roast)}&lang=${encodeURIComponent(row.lang ?? 'en')}&bucket=${encodeURIComponent(row.bucket ?? 'general')}`;
  const appUrl = siteUrl ? `${siteUrl}/roast/${row.id}` : '#';

  return `<!doctype html>
<html lang="${row.lang === 'ml' ? 'ml' : 'en'}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BURN (കത്തൽ) — “${escapeHtml(roast)}”</title>
    <meta name="description" content="A savage roast generated by BURN (കത്തൽ). Come in a mood, leave worse. 0% encouragement guaranteed." />
    <meta property="og:type" content="article" />
    <meta property="og:site_name" content="BURN (കത്തൽ)" />
    <meta property="og:title" content="“${escapeHtml(roast)}”" />
    <meta property="og:description" content="Roasted by BURN (കത്തൽ) — 0% encouragement guaranteed." />
    <meta property="og:image" content="${escapeHtml(ogImage)}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:image" content="${escapeHtml(ogImage)}" />
    <meta name="theme-color" content="#0a0a0a" />
    <style>
      body { margin: 0; background: #0a0a0f; color: #f2f1f6; font-family: 'Segoe UI', system-ui, sans-serif; min-height: 100vh; display: flex; align-items: center; justify-content: center; }
      .card { max-width: 640px; margin: 32px; padding: 40px; border: 1px solid #23202c; border-radius: 20px; background: #12101a; }
      .brand { font-size: 15px; color: #8b8b96; letter-spacing: 1px; }
      .roast { font-size: 24px; line-height: 1.5; margin: 20px 0 8px; }
      .tag { display: inline-block; padding: 6px 14px; border-radius: 999px; border: 1px solid #2b2836; color: #ffb4ae; font-size: 14px; margin-bottom: 16px; }
      .cta { display: inline-block; margin-top: 12px; padding: 12px 22px; border-radius: 999px; background: #ff5148; color: #0a0a0f; text-decoration: none; font-weight: 700; }
      .foot { margin-top: 18px; color: #6f6c7a; font-size: 13px; }
    </style>
  </head>
  <body>
    <div class="card">
      <div class="brand">BURN · കത്തൽ — 0% encouragement guaranteed</div>
      <div class="tag">${emoji} ${escapeHtml(bucketLabel)}</div>
      <div class="roast">“${escapeHtml(roast)}”</div>
      <a class="cta" href="${escapeHtml(appUrl)}">Make your own roast 💀</a>
      <div class="foot">Come in a mood, leave worse.</div>
    </div>
  </body>
</html>`;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  const url = new URL(req.url);
  const id = (url.searchParams.get('id') ?? '').trim();
  if (!id) {
    return new Response('Missing id', { status: 400, headers: corsHeaders });
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? '';
  const siteUrl = Deno.env.get('SITE_URL') ?? '';

  const row = await fetchSubmission(id);
  if (!row) {
    return new Response('Roast not found', { status: 404, headers: corsHeaders });
  }

  const html = renderPage(row, supabaseUrl, siteUrl);

  return new Response(html, {
    headers: {
      ...corsHeaders,
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'public, max-age=300, s-maxage=900',
    },
  });
});
